# Onboarding API

openapi: 3.0.3

info:
  title: Onboarding API
  version: '1.3'
  
servers:
  - url : http://STD22089.com
  
paths: 
  /students:
    get:
      tags:
        - students
      summary: Get all students 
      description: Return informations about all students
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '500':
          description: Internal Server error
    
    post:
      tags: 
        - students
      summary: Add a new student
      description: Add a new student
      requestBody:
        description: Create a new student 
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      
      responses:
        '200': 
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '500':
          description: Internal Server error
  
components:
  schemas:
    Student:
      required:
        - id
        - name
        - birthdate
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: andy
        birthdate:
          type: string
          format: date #require react-