openapi: 3.0.3
info:
  title: Onboarding API
  version: '1.0.2'
  description: >-
    Firstname : Andy Avotiana 


    Lastname : Razafindrakoto


    STD22089


    This specification describes the data model and API used for onboarding
    students to HEI
servers:
  - url: http://STD22089.com
paths:
  /students:
    get:
      tags:
        - students
      summary: Get all students
      description: Return informations about all students
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '500':
          description: Internal Server error
    post:
      tags:
        - students
      summary: Add a new student
      description: Add a new student
      requestBody:
        description: Created student object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '500':
          description: Internal Server error
components:
  schemas:
    Student:
      required:
        - id
        - name
        - birthdate
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: andy
        birthdate:
          type: string
          format: date
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        birthdate:
          type: string
          format: date